### ISSUE TITLE
A Pirate's Ploy hangs app

### ISSUE THREAD

**Issue by timak87** [GlowPuff/ImperialCommander#37]
v.14. 
Windows and Android
Loading mission: A Pirate's Ploy hangs app.

**Comment by Noldorion** [comment]
Additional info: This is mission "other39". It happens in no other mission. I assume this has something to do with the custom group (DG070) being added to the initial groups, since this is the only mission with a custom group in the initial setup. 

If that turns out to be true, you can simply remove it from the initial groups - the mission info file tells the players to deploy the custom group anyway, and it works the same way in "Test of Metal", so there's really no need to include it.

**Comment by GlowPuff** [comment]
Yes, that would explain it.  The custom group DG070 doesn't have a "real" card in the virtual deck that's created at startup.  It's a special case item that's added as-needed.  The app is silently halting because it's reading a null value from the startup deck.  We can either remove that item from the mission preset, OR I could just add it to the virtual deck that's created at startup, so it can be found.

**Comment by GlowPuff** [comment]
Fixed! (for the next published update v.15)
Heads up for future translations: In the **instructions.json** file, the first entry now looks like this below.  The instID has changed from "DG1000" to "DG070".  I've already applied this change to all the current language files.

{
			"instName": "Manual Deployment",
			"instID": "DG070",
			"content": [
				{
					"instruction": [
						"See Mission Rules.",
					]
				},
			],
		},
