### ISSUE TITLE
Suggestion: Activation button (et al.) scale on small screens

### ISSUE THREAD

**Issue by Noldorion** [GlowPuff/ImperialCommander#47]
From Austen (OZ10):
Just started a new campaign and have come back to this truly excellent app - thanks again to all those involved.

A little feedback if you'll allow. I use the app on phone and some of toggles are quite difficult to press without pressing something else. This is even more obvious with the new activation toggles (which are a great idea!). Any chance the ui could scale certain toggles / buttons if the user is playing on a small screen? Might be difficult to do but thought I'd ask.

https://boardgamegeek.com/thread/2611941/article/39410297#39410297

**Comment by GlowPuff** [comment]
I made the activation toggles larger, hopefully it's enough.  Any larger and they will just start covering the hero icon too much (which is also clickable).  I've made some of the other interface elements larger in the past, as well, so those are already as large as I can make them before they interfere with other elements.  To be honest, we never considered the phone as a device people would use, so I didn't account for it at all.  Anyways, hopefully this helps!

This will be in the next update, which may be awhile since we are adding new features.
